### ISSUE TITLE
Corrected the excessive garbage generated by `new Axios()`

### ISSUE THREAD

**Issue by 011011100** [xiao-akatsuki/axios#1]
**Describe what you would like to know or do**
Corrected the excessive garbage generated by `new Axios()`

**Describe the solution you'd considered**
```java
	public static Axios post(String url) throws Exception{
		return post(url,null,null);
	}
```

**Comment by xiaoxunyao** [comment]
yep, your solution solves this problem very well, thank you for your support to Axios
